Table clientes {
    id int [pk, increment]
    tipo_cliente int
    tipo_documento varchar(3)  // DNI o RUC
    numero_documento varchar(13)
    nombres varchar(100)
    razon_social varchar(100)
    telefono int
    fecha_nac date
    correo varchar(100)
    direccion varchar(100)
    referencia varchar(100)
    estado varchar(5) [default: 'a']

    created_at datetime
    updated_at datetime
}

Table combos {
    id int [pk, increment]
    nombre varchar(255)
    id_area int [ref: > areas_produccion.id]
    nota text
    descripcion text
    imagen varchar(255)
    estado enum('activo','inactivo')
    delivery boolean

    created_at datetime
    updated_at datetime
}


Table productos {
    id int [pk, increment]
    id_catg int [ref: > producto_categorias.id_catg]
    id_areap int [ref: > areas_produccion.id]
    nombre varchar(255)
    notas text
    descripcion text
    imagen varchar(255) //  ruta de la imagen
    codigo_qr varchar(255) //  QR del producto (opcional)
    codigo_barra varchar(100) //  para escáner
    precio decimal(10,2) //  PRECIO (CLAVE)
    costo decimal(10,2) //  opcional para ganancias
    stock int //  control de inventario
    stock_minimo int //  alerta de stock bajo
    preparacion enum('cocina', 'bodega')
    tiempo_preparacion int //  minutos
    delivery boolean
    destacado boolean //  producto destacado
    estado char(1) // a = activo, i = inactivo
    orden int

    created_at datetime
    updated_at datetime
}

Table areas_produccion {
    id int [pk, increment]
    nombre varchar(255)
    impresora_id int [ref: > impresoras.id] 
    estado char(1)
    created_at datetime
    updated_at datetime
}

Table usuarios {
    id int [pk, increment]
    dni varchar
    nombres varchar
    apellido_paterno varchar
    apellido_materno varchar
    email varchar
    cargo_rrhh varchar
    foto varchar
    username varchar
    password varchar
    rol varchar
    estado int
    created_at datetime
    updated_at datetime
}

Table producto_categorias {
    id_catg int [pk, increment]
    descripcion varchar(100)
    delivery boolean
    orden int
    imagen varchar(255)
    estado char(1)
    created_at datetime
    updated_at datetime
}

Table cajas {
    id int [pk, increment]
    nombre varchar(100)
    estado char(1)
    fecha_apertura datetime
    fecha_cierre datetime
    created_at datetime
    updated_at datetime
}

Table caja_usuario {
    id int [pk, increment]
    caja_id int [ref: > cajas.id]
    usuario_id int [ref: > usuarios.id]
    created_at datetime
    updated_at datetime
}

Table salons {
    id_salon int [pk, increment]
    nombre varchar(100) [not null]
    estado enum('activo', 'inactivo')
    created_at timestamp
    updated_at timestamp
}

Table mesas {
    id_mesa int [pk, increment]
    id_salon int [ref: > salons.id_salon]
    nombre varchar(10)
    estado enum('activo', 'ocupado', 'inactivo')
    created_at timestamp
    updated_at timestamp
}

Table impresoras { 
    id bigint [pk, increment]
    nombre varchar(100) [not null]
    estado enum('activo','inactivo') [default: 'activo']
    created_at timestamp
    updated_at timestamp
}

Table tipo_documentos {
    id bigint [pk, increment]
    descripcion varchar(100)
    serie varchar(10)
    numero varchar(20)
    estado enum('activo','inactivo') [default: 'activo']
    created_at timestamp
    updated_at timestamp
}

Table tipo_pagos {
    id bigint [pk, increment]
    descripcion varchar(100)
    created_at timestamp
    updated_at timestamp
}

Table metodo_pagos {
    id bigint [pk, increment]
    tipo_pago_id bigint [ref: > tipo_pagos.id]
    estado enum('activo','inactivo') [default: 'activo']
    descripcion varchar(100)
    created_at timestamp
    updated_at timestamp
}

Table empresas {
    id bigint [pk, increment]

    ruc char(11) [not null, unique]
    razon_social varchar(255) [not null]
    nombre_comercial varchar(255)

    direccion_comercial varchar(255)
    direccion_fiscal varchar(255)

    ubigeo char(6)
    departamento varchar(100)
    provincia varchar(100)
    distrito varchar(100)

    modo enum('produccion','beta') [default: 'beta']

    usuariosol varchar(100)
    clave_sol text
    clavecertificado text

    logo varchar(255)
    celular varchar(20)
    email varchar(150)

    created_at timestamp
    updated_at timestamp
}

Table reclamos {
    id bigint [pk, increment]
    tipo_documento varchar(20)
    numero_documento varchar(20)
    primer_nombre varchar(100)
    segundo_nombre varchar(100)
    primer_apellido varchar(100)
    segundo_apellido varchar(100)
    correo varchar(150)
    telefono varchar(20)
    direccion varchar(255)
    departamento varchar(100)
    provincia varchar(100)
    distrito varchar(100)
    servicio_contratado varchar(255)
    numero_orden varchar(50)
    identificacion_servicio varchar(100)
    monto_reclamado decimal(10,2)
    tipo_reclamo varchar(20)
    motivo text
    detalle_solicitud text
    pedido_concreto text
    acepto_politicas boolean [default: true]

    created_at timestamp
    updated_at timestamp
}

Table settings {
    id bigint [pk, increment]
    key varchar(255) [not null]
    value text
    created_at timestamp
    updated_at timestamp
}