Table salons {
    id_salon int [pk, increment]
    nombre varchar(100) [not null]
    estado enum('activo', 'inactivo')
    created_at timestamp
    updated_at timestamp
}

Table mesa {
    id_mesa int [pk, increment]
    id_salon int [ref: > salons.id_salon]
    nombre varchar(10) // M01, M02...
    estado enum('activo', 'ocupado', 'inactivo')
    created_at timestamp
    updated_at timestamp
}

Table inpresoras {
    id bigint [pk, increment, note: 'ID único autoincrementable']
    nombre varchar(100) [not null, note: 'Ej: EPSON TM-T20II']
    estado enum('activo','inactivo') [default: 'activo']
    created_at timestamp
    updated_at timestamp
}

Table tipo_documentos {
    id bigint [pk, increment, note: 'ID único autoincrementable']
    descripcion varchar [note: 'Ej: BOLETA, FACTURA, NOTA DE CREDITO']
    serie varchar [note: 'Ej: B001, F001']
    numero varchar [note: 'Correlativo del documento']
    estado enum('activo','inactivo') [default: 'activo']
    created_at timestamp
    updated_at timestamp
}

Table tipo_pagos{
    id bigint [pk, increment, note: 'ID único autoincrementable']
    descripcion varchar 

    created_at timestamp
    updated_at timestamp
}
Table metodopagos{
    id bigint [pk, increment, note: 'ID único autoincrementable']
    tipo_pago_id bigint [not null, ref: > tipo_pagos.id]
    estado enum('activo','inactivo') [default: 'activo']
    descripcion varchar 

    created_at timestamp
    updated_at timestamp
}

Table empresas {
    id bigint [pk, increment]

    ruc char(11) [not null, unique]
    razon_social varchar(255) [not null]
    nombre_comercial varchar(255)

    direccion_comercial varchar(255)
    direccion_fiscal varchar(255)

    ubigeo char(6)
    departamento varchar(100)
    provincia varchar(100)
    distrito varchar(100)

    modo enum('produccion','beta') [default: 'beta']

    usuariosol varchar(100)
    clave_sol text
    clavecertificado text

    logo varchar(255)
    celular varchar(20)
    email varchar(150)

    created_at timestamp
    updated_at timestamp
}


Table reclamos {
    id bigint [pk, increment, note: 'ID único autoincrementable']
    tipo_documento varchar [note: 'DNI, CE, RUC, Pasaporte']
    numero_documento varchar
    primer_nombre varchar
    segundo_nombre varchar [null, note: 'Opcional']
    primer_apellido varchar
    segundo_apellido varchar
    correo varchar
    telefono varchar
    direccion varchar
    departamento varchar
    provincia varchar
    distrito varchar
    servicio_contratado varchar
    numero_orden varchar [null, note: 'Opcional']
    identificacion_servicio varchar [null, note: 'Opcional']
    monto_reclamado decimal(10,2) [null, note: 'Monto en Soles (S/.)']
    tipo_reclamo varchar [note: 'Reclamo o Queja']
    motivo text
    detalle_solicitud text
    pedido_concreto text
    acepto_politicas boolean [default: true]

    created_at timestamp
    updated_at timestamp
}

Table settings {
    id bigint [pk, increment]
    key varchar(255) [not null]
    value text
    created_at timestamp
    updated_at timestamp
}

